export const SHOW_ONBOARDING = 'SHOW_ONBOARDING';
export const SECRETARIUM_TRANSACTION_ACKNOWLEDGED = 'SECRETARIUM_TRANSACTION_ACKNOWLEDGED';
export const SECRETARIUM_TRANSACTION_PROPOSED = 'SECRETARIUM_TRANSACTION_PROPOSED';
export const SECRETARIUM_TRANSACTION_COMMITED = 'SECRETARIUM_TRANSACTION_COMMITED';
export const SECRETARIUM_TRANSACTION_EXECUTED = 'SECRETARIUM_TRANSACTION_EXECUTED';

