name: Node.js Mutation Testing

on:
  push:
    branches:
      - master
      - test/**

jobs:

  test:
    name: Mutating tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn test:mutation
      env:
        CI: true
        STRYKER_DASHBOARD_API_KEY: ${{ secrets.stryker_token }}
