name: Node.js CI

on: [push]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn lint
      env:
        CI: true

  test:
    name: Testing
    runs-on: ${{ matrix.os-version }}
    needs: lint

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os-version: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn test
      env:
        CI: true
